# SPDX-FileCopyrightText: 2026 Sam Hanes <sam@maltera.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ammaraskar/sphinx-action@9.0.4
        with:
          docs-folder: src

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
